# Programas del proyecto

sources = [
    'instruments/instrument.cpp',
    'instruments/instrument_dumb.cpp',

    'instruments/seno.cpp',
    'instruments/seno_fm.cpp',
    'instruments/strings.cpp',
    'instruments/percussion.cpp',
    'instruments/percussion_pitch.cpp',
    'instruments/percussion_sample.cpp',

    'synth/envelope_adsr.cpp',
    'synth/midi_score.cpp',
    'synth/multinote_instr.cpp',
    'synth/orchest.cpp',
    'synth/synthesizer.cpp',

    'effects/effect.cpp',
    'effects/tremolo.cpp',
    'effects/vibrato.cpp',
    'effects/distortion.cpp',
]


executable(
    'synth',
    sources: sources,
    include_directories: inc,
    link_args: ['-lm', '-lsndfile'],
    link_with: lib_pav,
    install: true,
)
